#Start this docker-compose file use 'docker-compose up -d' <- this will also create the container
#Stop the container with 'docker-compose down' <- this will also delete the container
#Open http://localhost:9090/graph  for the prometheus graph

version: "1"
services:
  penalty-database:
    image: mongo
    ports:
      - 27017:27017
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./data/db:/data/db"

  penalty-server:
    image: openjdk:11
    ports:
      - 8088:8088
    volumes:
      - "./build/libs/de.vexxes.penaltycatalogserver-0.0.1.jar:/opt/penaltycatalogserver.jar"
    command: [ 'java', '-jar', '/opt/penaltycatalogserver.jar' ]
    links:
      - "penalty-database:database"

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_ADMIN: admin
#      default password is bitnami
#      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_DATABASE_NAME: keycloak

  postgresql:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password